### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lbenedix** [eruvanos/retro-cli#1]
my mac os setup is completely broken now, worst software ever

**Comment by luistesperanca** [comment]
Please provide a reason, and what version you are using

**Comment by lbenedix** [comment]
The only version

**Comment by luistesperanca** [comment]
Please still specify it, it's important for us

**Comment by eruvanos** [comment]
Hi,
thank you for the hint, that something does not work.
While you description is missing a few details (like what doesn't work, or which OS you run on),
I was able to deduct those information from other issues you created at Github projects, mostly about Mac M1 support.

I did not update the dependencies for a while, which was the reason, that Mac M1 was not supported by the ngrok dependency used.

The issue is now fixed and you should be able to do your next retro in the command line.
